#pragma once
// Generated by task4_code/image_processing.ipynb for Task 4.2
// Start position in 5x5 zone: (50, 350)
// Goal position in 5x5 zone: (450, 150)

struct WaypointCmd {
    float turn_deg;
    float drive_mm;
};

constexpr int NUM_WAYPOINTS = 3;
constexpr WaypointCmd OBSTACLE_ROUTE[NUM_WAYPOINTS] = {
    {88.6, 226.9}, {-43.4, 342.4}, {20.4, 274.7}
};
