#pragma once
// Generated by task4_code/image_processing.ipynb for Task 4.2
// Start position in 5x5 zone: (45, 345)
// Goal position in 5x5 zone: (445, 145)

struct WaypointCmd {
    float turn_deg;
    float drive_mm;
};

constexpr int NUM_WAYPOINTS = 4;
constexpr WaypointCmd OBSTACLE_ROUTE[NUM_WAYPOINTS] = {
    {54.9, 272.9}, {-50.1, 190.7}, {83.7, 269.4}, {45.9, 94.7}
};
