#pragma once

// Generated by task4_code/image_processing.ipynb from actualmaze.jpg
// 9x9 maze (rows x cols).
// Start (1, 3) facing W  ->  goal (1, 4), 53 moves.
//
//   +---+---+---+---+---+---+---+---+---+
//   |   |   | *   * | *   *   * |   |   |
//   +---+---+   +   +   +---+   +   +---+
//   |   | *   * | S | G |     *   * |   |
//   +   +   +---+---+---+---+---+   +   +
//   |     * |               |     *   * |
//   +   +   +   +   +   +   +---+---+   +
//   | *   * | *   *   *   *   * | *   * |
//   +   +---+   +   +   +   +   +   +---+
//   | * |   | * |           | * | * |   |
//   +   +   +   +---+---+---+   +   +   +
//   | * | *   * | *   *   * | * | *   * |
//   +   +   +   +   +---+   +   +---+   +
//   | *   * |   | *   * | *   * | *   * |
//   +---+---+---+---+   +---+---+   +   +
//   |   |     *   *   * | *   *   * |   |
//   +---+   +   +---+---+   +---+   +---+
//   |   |     *   *   *   *     |   |   |
//   +---+---+---+---+---+---+---+---+---+
//
// Usage:  chainMovement(mouse, MAZE_ROUTE);

constexpr int   MAZE_ROWS     = 9;
constexpr int   MAZE_COLS     = 9;
constexpr int   MAZE_MOVES    = 53;
constexpr char  MAZE_START_DIR = 'W';
constexpr char  MAZE_ROUTE[]  = "rflflfrflffrflffflflfrflffrffffrfffrfrflfflflfrfrfflflffflfrfflfrflflfrffrflflfrflfrflfflf";
